/* tslint:disable */
/* eslint-disable */
/**
 * 钉钉开放平台
 * 集成钉钉开放平台<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DingTalkCardData } from './ding-talk-card-data';
import { DingTalkOpenDeliverModel } from './ding-talk-open-deliver-model';
import { OpenDynamicDataConfig } from './open-dynamic-data-config';
import { OpenSpaceModel } from './open-space-model';
import { PrivateData } from './private-data';
 /**
 * 
 *
 * @export
 * @interface DingTalkCreateAndDeliverInput
 */
export interface DingTalkCreateAndDeliverInput {

    /**
     * 卡片创建者的userId
     *
     * @type {string}
     * @memberof DingTalkCreateAndDeliverInput
     */
    userId?: string | null;

    /**
     * 卡片内容模板ID
     *
     * @type {string}
     * @memberof DingTalkCreateAndDeliverInput
     */
    cardTemplateId: string;

    /**
     * 外部卡片实例Id
     *
     * @type {string}
     * @memberof DingTalkCreateAndDeliverInput
     */
    outTrackId: string;

    /**
     * 卡片回调的类型：STREAM：stream模式 HTTP：http模式
     *
     * @type {string}
     * @memberof DingTalkCreateAndDeliverInput
     */
    callbackType?: string | null;

    /**
     * 卡片回调HTTP模式时的路由 Key，用于查询注册的 callbackUrl。
     *
     * @type {string}
     * @memberof DingTalkCreateAndDeliverInput
     */
    callbackRouteKey?: string | null;

    /**
     * @type {DingTalkCardData}
     * @memberof DingTalkCreateAndDeliverInput
     */
    cardData: DingTalkCardData;

    /**
     * @type {PrivateData}
     * @memberof DingTalkCreateAndDeliverInput
     */
    crivateData?: PrivateData;

    /**
     * @type {OpenDynamicDataConfig}
     * @memberof DingTalkCreateAndDeliverInput
     */
    openDynamicDataConfig?: OpenDynamicDataConfig;

    /**
     * @type {OpenSpaceModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    imSingleOpenSpaceModel?: OpenSpaceModel;

    /**
     * @type {OpenSpaceModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    imGroupOpenSpaceModel?: OpenSpaceModel;

    /**
     * @type {OpenSpaceModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    imRobotOpenSpaceModel?: OpenSpaceModel;

    /**
     * @type {OpenSpaceModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    coFeedOpenSpaceModel?: OpenSpaceModel;

    /**
     * @type {OpenSpaceModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    topOpenSpaceModel?: OpenSpaceModel;

    /**
     * 表示场域及其场域id
     *
     * @type {string}
     * @memberof DingTalkCreateAndDeliverInput
     */
    openSpaceId: string;

    /**
     * @type {DingTalkOpenDeliverModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    imSingleOpenDeliverModel?: DingTalkOpenDeliverModel;

    /**
     * @type {DingTalkOpenDeliverModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    imGroupOpenDeliverModel?: DingTalkOpenDeliverModel;

    /**
     * @type {DingTalkOpenDeliverModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    imRobotOpenDeliverModel?: DingTalkOpenDeliverModel;

    /**
     * @type {DingTalkOpenDeliverModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    topOpenDeliverModel?: DingTalkOpenDeliverModel;

    /**
     * @type {DingTalkOpenDeliverModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    coFeedOpenDeliverModel?: DingTalkOpenDeliverModel;

    /**
     * @type {DingTalkOpenDeliverModel}
     * @memberof DingTalkCreateAndDeliverInput
     */
    docOpenDeliverModel?: DingTalkOpenDeliverModel;

    /**
     * 用户userId类型:1（默认）：userId模式 2：unionId模式
     *
     * @type {number}
     * @memberof DingTalkCreateAndDeliverInput
     */
    userIdType?: number;
}
