/* tslint:disable */
/* eslint-disable */
/**
 * 钉钉开放平台
 * 集成钉钉开放平台<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DingTalkOpenDeliverModel
 */
export interface DingTalkOpenDeliverModel {

    /**
     * 用于发送卡片的机器人编码。
     *
     * @type {string}
     * @memberof DingTalkOpenDeliverModel
     */
    robotCode?: string | null;

    /**
     * 消息@人。格式：{\"key\":\"value\"}。key：用户的userId value：用户名
     *
     * @type {{ [key: string]: string; }}
     * @memberof DingTalkOpenDeliverModel
     */
    atUserIds?: { [key: string]: string; } | null;

    /**
     * 指定接收人的userId。
     *
     * @type {Array<string>}
     * @memberof DingTalkOpenDeliverModel
     */
    recipients?: Array<string> | null;

    /**
     * 扩展字段，示例如下：{\"key\":\"value\"}
     *
     * @type {{ [key: string]: string; }}
     * @memberof DingTalkOpenDeliverModel
     */
    extension?: { [key: string]: string; } | null;

    /**
     * IM机器人单聊若未设置其他投放属性，需设置spaeType为IM_ROBOT。
     *
     * @type {string}
     * @memberof DingTalkOpenDeliverModel
     */
    spaceType?: string | null;

    /**
     * 过期时间戳。若使用topOpenDeliverModel对象，则该字段必填。
     *
     * @type {number}
     * @memberof DingTalkOpenDeliverModel
     */
    expiredTimeMillis?: number;

    /**
     * 可以查看该吊顶卡片的userId。
     *
     * @type {Array<string>}
     * @memberof DingTalkOpenDeliverModel
     */
    userIds?: Array<string> | null;

    /**
     * 可以查看该吊顶卡片的设备：android｜ios｜win｜mac。
     *
     * @type {Array<string>}
     * @memberof DingTalkOpenDeliverModel
     */
    platforms?: Array<string> | null;

    /**
     * 业务标识。
     *
     * @type {string}
     * @memberof DingTalkOpenDeliverModel
     */
    bizTag?: string | null;

    /**
     * 协作场域下的排序时间。
     *
     * @type {number}
     * @memberof DingTalkOpenDeliverModel
     */
    gmtTimeLine?: number;

    /**
     * 员工userId信息
     *
     * @type {string}
     * @memberof DingTalkOpenDeliverModel
     */
    userId?: string | null;
}
