/* tslint:disable */
/* eslint-disable */
/**
 * 钉钉开放平台
 * 集成钉钉开放平台<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Approver } from './approver';
import { FormComponentValue } from './form-component-value';
import { TargetSelectActioner } from './target-select-actioner';
 /**
 * 
 *
 * @export
 * @interface DingTalkWorkflowProcessInstancesInput
 */
export interface DingTalkWorkflowProcessInstancesInput {

    /**
     * 发起人用户ID
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    originatorUserId?: string | null;

    /**
     * 审批模板的流程编码
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    processCode?: string | null;

    /**
     * 部门ID
     *
     * @type {number}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    deptId?: number;

    /**
     * 微应用AgentId
     *
     * @type {number}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    microappAgentId?: number;

    /**
     * 审批人列表（支持多节点）
     *
     * @type {Array<Approver>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    approvers?: Array<Approver> | null;

    /**
     * 抄送人列表
     *
     * @type {Array<string>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    ccList?: Array<string> | null;

    /**
     * 抄送位置：START（开始），MIDDLE（中间），END（结束）
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    ccPosition?: string | null;

    /**
     * 目标动态选择办理人（用于会签或或签等场景）
     *
     * @type {Array<TargetSelectActioner>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    targetSelectActioners?: Array<TargetSelectActioner> | null;

    /**
     * 表单组件值列表
     *
     * @type {Array<FormComponentValue>}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    formComponentValues?: Array<FormComponentValue> | null;

    /**
     * 请求ID，用于幂等控制
     *
     * @type {string}
     * @memberof DingTalkWorkflowProcessInstancesInput
     */
    requestId?: string | null;
}
