/* tslint:disable */
/* eslint-disable */
/**
 * 钉钉开放平台
 * 集成钉钉开放平台<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Notification } from './notification';
import { SearchSupport } from './search-support';
 /**
 * 
 *
 * @export
 * @interface OpenSpaceModel
 */
export interface OpenSpaceModel {

    /**
     * 吊顶场域属性，通过增加spaeType使卡片支持吊顶场域。
     *
     * @type {string}
     * @memberof OpenSpaceModel
     */
    spaceType?: string | null;

    /**
     * 卡片标题。
     *
     * @type {string}
     * @memberof OpenSpaceModel
     */
    title?: string | null;

    /**
     * 酷应用编码。
     *
     * @type {string}
     * @memberof OpenSpaceModel
     */
    coolAppCode?: string | null;

    /**
     * 是否支持转发, 默认false。
     *
     * @type {boolean}
     * @memberof OpenSpaceModel
     */
    supportForward?: boolean | null;

    /**
     * 支持国际化的LastMessage。
     *
     * @type {{ [key: string]: string; }}
     * @memberof OpenSpaceModel
     */
    lastMessageI18n?: { [key: string]: string; } | null;

    /**
     * @type {SearchSupport}
     * @memberof OpenSpaceModel
     */
    searchSupport?: SearchSupport;

    /**
     * @type {Notification}
     * @memberof OpenSpaceModel
     */
    notification?: Notification;
}
