/* tslint:disable */
/* eslint-disable */
/**
 * 钉钉开放平台
 * 集成钉钉开放平台<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TaskItem
 */
export interface TaskItem {

    /**
     * @type {string}
     * @memberof TaskItem
     */
    result?: string | null;

    /**
     * @type {string}
     * @memberof TaskItem
     */
    activityId?: string | null;

    /**
     * @type {string}
     * @memberof TaskItem
     */
    pcUrl?: string | null;

    /**
     * @type {Date}
     * @memberof TaskItem
     */
    createTime?: Date | null;

    /**
     * @type {string}
     * @memberof TaskItem
     */
    mobileUrl?: string | null;

    /**
     * @type {string}
     * @memberof TaskItem
     */
    userId?: string | null;

    /**
     * @type {number}
     * @memberof TaskItem
     */
    taskId?: number;

    /**
     * @type {string}
     * @memberof TaskItem
     */
    status?: string | null;
}
