/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IpAddressInfo } from './ip-address-info';
import { NetworkInterfaceStatistics } from './network-interface-statistics';
 /**
 * 
 *
 * @export
 * @interface NetworkInfo
 */
export interface NetworkInfo {

    /**
     * @type {string}
     * @memberof NetworkInfo
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof NetworkInfo
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof NetworkInfo
     */
    type?: string | null;

    /**
     * @type {string}
     * @memberof NetworkInfo
     */
    operationalStatus?: string | null;

    /**
     * @type {string}
     * @memberof NetworkInfo
     */
    speed?: string | null;

    /**
     * @type {string}
     * @memberof NetworkInfo
     */
    physicalAddress?: string | null;

    /**
     * @type {boolean}
     * @memberof NetworkInfo
     */
    supportsMulticast?: boolean;

    /**
     * @type {boolean}
     * @memberof NetworkInfo
     */
    isReceiveOnly?: boolean;

    /**
     * @type {Array<string>}
     * @memberof NetworkInfo
     */
    dnsAddresses?: Array<string> | null;

    /**
     * @type {Array<string>}
     * @memberof NetworkInfo
     */
    gatewayAddresses?: Array<string> | null;

    /**
     * @type {Array<string>}
     * @memberof NetworkInfo
     */
    dhcpServerAddresses?: Array<string> | null;

    /**
     * @type {Array<IpAddressInfo>}
     * @memberof NetworkInfo
     */
    iPv4Addresses?: Array<IpAddressInfo> | null;

    /**
     * @type {Array<IpAddressInfo>}
     * @memberof NetworkInfo
     */
    iPv6Addresses?: Array<IpAddressInfo> | null;

    /**
     * @type {NetworkInterfaceStatistics}
     * @memberof NetworkInfo
     */
    statistics?: NetworkInterfaceStatistics;
}
